### ISSUE TITLE
Value not in range: 9, exiting with code 2

### ISSUE THREAD

**Issue by boonjun-marslab** [localizely/intl_utils#49]
I cannot update dart file from arb to dart.

```
**flutter pub run intl_utils:generate -v**
[ +138 ms] executing: [/Users/marslab/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [/Users/marslab/flutter/] git tag --points-at HEAD
[ +142 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[  +15 ms] executing: [/Users/marslab/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +24 ms] executing: [/Users/marslab/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +56 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +17 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +22 ms] Using /Users/marslab/flutter/.pub-cache for the pub cache.
[   +2 ms] executing: /Users/marslab/flutter/bin/cache/dart-sdk/bin/pub run intl_utils:generate -v
ERROR: Failed to generate localization files.
RangeError: Value not in range: 9
[+1391 ms] "flutter run" took 1,490ms.
[   +5 ms] pub finished with exit code 2
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:375:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:260:15)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #7      _rootRun (dart:async/zone.dart:1190:13)
           #8      _CustomZone.run (dart:async/zone.dart:1093:19)
           #9      _runZoned (dart:async/zone.dart:1630:10)
           #10     runZoned (dart:async/zone.dart:1550:10)
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #15     _rootRunUnary (dart:async/zone.dart:1198:47)
           #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #22     _rootRun (dart:async/zone.dart:1190:13)
           #23     _CustomZone.run (dart:async/zone.dart:1093:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +6 ms] ensureAnalyticsSent: 0ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +3 ms] exiting with code 2
```
```
**marslab@Marslabs-MacBook-Pro ufresh-app % flutter doctor -v**
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/marslab/flutter
    • Framework revision 9b2d32b605 (4 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/marslab/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 24E54E56-FF22-4F1F-B7CD-05560BA2C856 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

! Doctor found issues in 1 category.
```

**Comment by lzoran** [comment]
Hi @boonjun-marslab,

Thanks for reporting this!

I've tried to reproduce it, but without success.

1. Could you check if all your ARB files are valid (well-formatted)?

2. Could you confirm that this error occurs on each run (maybe some other processes changing the required files during generation)?

3. Could you check if cleaning the project helps?
```
cd project_root
flutter clean
flutter pub get
flutter pub run intl_utils:generate
```

**Comment by boonjun-marslab** [comment]
**flutter clean**
```
flutter pub get
flutter pub run intl_utils:generate
Cleaning Xcode workspace...                                        48.7s
Deleting build...                                                9,679ms (!)
Deleting .dart_tool...                                             449ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            0ms
Deleting App.framework...                                          193ms
Deleting Flutter.podspec...                                          1ms
Deleting .flutter-plugins-dependencies...                            3ms
Deleting .flutter-plugins...                                         1ms
Running "flutter pub get" in ufresh-app...                          2.0s
ERROR: Failed to generate localization files.
RangeError: Value not in range: 9
pub finished with exit code 2

```

Below is the arb file

[arb.zip](https://github.com/localizely/intl_utils/files/6508183/arb.zip)

**Comment by lzoran** [comment]
Hi @boonjun-marslab,

On windows I have encountered on a different error message (check attached image bellow).

![error](https://user-images.githubusercontent.com/15170421/118804728-59c30600-b8a5-11eb-9757-f98f57ddcd9e.png)

Fixing typo in the `intl_ms.arb` file solved the problem (`stok` -> `stock`).
```
...
"onlyHave": "Maaf, buat masa ini, kami hanya mempunyai {stock} kuantiti produk ini.",
...
```

Not sure why I got different error message.
If this does not solve your issue, I'll try to reproduce it again on the mac.

**Comment by boonjun-marslab** [comment]
Yes, error still produce. I am using mac os. I had run `flutter pub cache repair ` also. Same error produce.

**Comment by aleksakrstic** [comment]
Hi @boonjun-marslab 
I get the same error message as @lzoran when I run the command for your ARB files...

Could you try again but runnging these commands instead:
- `flutter pub global activate intl_utils 1.9.0`
- `flutter pub global run intl_utils:generate -v`

And see what it prints in that case?

**Comment by boonjun-marslab** [comment]
Hi, thanks for verify. I had done Izoran suggestion. Fixing typo in the intl_ms.arb file (stok -> stock). My problem still exist. 

Bellowing is detail running the commands.

**flutter pub global activate intl_utils 1.9.0**
```
Package intl_utils is currently active at version 1.9.0.
Resolving dependencies...
+ _fe_analyzer_shared 7.0.0 (21.0.0 available)
+ analyzer 0.39.17 (1.5.0 available)
+ archive 2.0.13 (3.1.2 available)
+ args 1.6.0 (2.1.0 available)
+ async 2.4.2 (2.7.0 available)
+ charcode 1.1.3 (1.2.0 available)
+ cli_util 0.2.0 (0.3.0 available)
+ collection 1.14.13 (1.15.0 available)
+ convert 2.1.1 (3.0.0 available)
+ crypto 2.1.5 (3.0.1 available)
+ csslib 0.16.2 (0.17.0 available)
+ dart_style 1.3.6 (2.0.1 available)
+ file 5.2.1 (6.1.1 available)
+ glob 1.2.0 (2.0.1 available)
+ html 0.14.0+4 (0.15.0 available)
+ http 0.12.2 (0.13.3 available)
+ http_parser 3.1.4 (4.0.0 available)
+ intl 0.16.1 (0.17.0 available)
+ intl_translation 0.17.10+1
+ intl_utils 1.9.0 (2.3.0 available)
+ js 0.6.2 (0.6.3 available)
+ meta 1.2.4 (1.3.0 available)
+ node_interop 1.2.1 (2.0.2 available)
+ node_io 1.2.0 (2.1.0 available)
+ package_config 1.9.3 (2.0.0 available)
+ path 1.7.0 (1.8.0 available)
+ pedantic 1.9.2 (1.11.0 available)
+ petitparser 3.1.0 (4.1.0 available)
+ pub_semver 1.4.4 (2.0.0 available)
+ source_span 1.7.0 (1.8.1 available)
+ string_scanner 1.0.5 (1.1.0 available)
+ term_glyph 1.1.0 (1.2.0 available)
+ typed_data 1.2.0 (1.3.0 available)
+ watcher 0.9.7+15 (1.0.0 available)
+ yaml 2.2.1 (3.1.0 available)
Precompiling executables...
Precompiled intl_utils:localizely_download.
Precompiled intl_utils:localizely_upload_main.
Precompiled intl_utils:generate.
Activated intl_utils 1.9.0.
```
**flutter pub global run intl_utils:generate -v**
```

[ +130 ms] executing: [/Users/marslab/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +63 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [/Users/marslab/flutter/] git tag --points-at HEAD
[ +102 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[  +13 ms] executing: [/Users/marslab/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +23 ms] executing: [/Users/marslab/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +58 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +18 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +12 ms] Using /Users/marslab/flutter/.pub-cache for the pub cache.
[   +1 ms] executing: /Users/marslab/flutter/bin/cache/dart-sdk/bin/pub global run intl_utils:generate -v
ERROR: Failed to generate localization files.
RangeError: Value not in range: 9
[ +606 ms] "flutter global" took 667ms.
[   +7 ms] pub finished with exit code 2
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:375:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:260:15)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #7      _rootRun (dart:async/zone.dart:1190:13)
           #8      _CustomZone.run (dart:async/zone.dart:1093:19)
           #9      _runZoned (dart:async/zone.dart:1630:10)
           #10     runZoned (dart:async/zone.dart:1550:10)
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #15     _rootRunUnary (dart:async/zone.dart:1198:47)
           #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #22     _rootRun (dart:async/zone.dart:1190:13)
           #23     _CustomZone.run (dart:async/zone.dart:1093:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +7 ms] ensureAnalyticsSent: 0ms
[   +5 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 2
```

**Comment by Chen-A-wi** [comment]
Hi, I have the same issue.

I use M1 mac air.

**Error Message**
```
/Users/benchen/Documents/Project/XXX-Flutter/.fvm/flutter_sdk/bin/flutter --no-color pub global run intl_utils:generate
ERROR: Failed to generate localization files.
RangeError: Value not in range: 9
pub finished with exit code 2
Process finished with exit code 2
```
![截圖 2021-10-14 下午4 22 38](https://user-images.githubusercontent.com/24693300/137279822-fc281641-cac5-410e-9c7d-f04c9f8fd768.png)

 **fvm flutter pub global run intl_utils:generate -v**
 
```
❯ fvm flutter pub global run intl_utils:generate -v

[ +238 ms] executing: sysctl hw.optional.arm64
[  +56 ms] Exit code 0 from: sysctl hw.optional.arm64
[   +7 ms] hw.optional.arm64: 1
[  +21 ms] executing: [/Users/benchen/fvm/versions/2.2.3/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +28 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +2 ms] executing: [/Users/benchen/fvm/versions/2.2.3/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +72 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] 2.2.3
[  +16 ms] executing: [/Users/benchen/fvm/versions/2.2.3/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/benchen/fvm/versions/2.2.3/] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +269 ms] executing: [/Users/benchen/fvm/versions/2.2.3/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +21 ms] executing: sw_vers -productName
[  +32 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +30 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 11.6
[        ] executing: sw_vers -buildVersion
[  +33 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 20G165
[ +141 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +95 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +83 ms] executing: /Users/benchen/fvm/versions/2.2.3/bin/cache/dart-sdk/bin/pub global run intl_utils:generate -v
ERROR: Failed to generate localization files.
RangeError: Value not in range: 9
[+2159 ms] "flutter global" took 2,383ms.
[  +35 ms] pub finished with exit code 2
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:368:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +118 ms] ensureAnalyticsSent: 110ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 2
```

**Comment by vintage** [comment]
Just had exact same problem in one of the projects. Not sure why it's been working correctly in other projects, but turned out the fix is to delete directory which contains auto generated files in my case `lib/generated` and regenerating the directory once again through CLI:

```
flutter pub run intl_utils:generate -v
flutter packages pub run build_runner build --delete-conflicting-outputs
```
