### ISSUE TITLE
How to unit test with localizations

### ISSUE THREAD

**Issue by wim07101993** [localizely/intl_utils#8]
When I use the generated localizations class, how can I unit test my widgets?

E.G:
Widget:
```dart
class HelloWorldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(Text(S.of(context).helloWorld));
  }
}
```
Unit Test:
```dart
void main() {
  testWidgets('HelloWorldWidget has hello world text',
      (WidgetTester tester) async {
    await tester.pumpWidget(HelloWorldWidget());

    final linkFinder = find.text('Hello World'); // this should be localized
    expect(linkFinder, findsOneWidget);
  });
}
```

Currently all I get is a null-ref exception.

**Comment by aleksakrstic** [comment]
Hi @wim07101993 
Could you compare your test with the this from Sample app: https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/test/localized_widget_test.dart and see if that works for you?

**Comment by wim07101993** [comment]
Hi,

The code helped a little bitt, the null-ref exception is gone but from the moment I add the custom localization delegate, the test does not find any text anymore...

code: 
```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:roger/generated/l10n.dart';

class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Roger',
      home: Text('Hello world'),
      locale: Locale('en'),
      localizationsDelegates: [
        S.delegate, // when this line is commented out, it works
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
    );
  }
}

void main() {
  testWidgets('widget should contain "Hello world" text',
      (WidgetTester tester) async {
    await tester.pumpWidget(TestApp());
    final textFinder = find.text('Hello world');
    expect(textFinder, findsOneWidget);
  });
}
```

exception:
```
Testing started at 09:36 ...

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "Hello world" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:...)
<asynchronous suspension>
#5      main.<anonymous closure> (file:....)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#18     withClock (package:clock/src/default.dart:48:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#86     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#120    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#128    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#129    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#139    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#148    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#149    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
(elided 111 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:... line 28
The test description was:
  widget should contain "Hello world" text
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: widget should contain "Hello world" text
```

**Comment by aleksakrstic** [comment]
Your code still differs from the sample project, for instance lines 28 & 29 from https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/test/localized_widget_test.dart .
Could you double check it?

**Comment by wim07101993** [comment]
Thanks but no still no change. The finder still does not find any widgets with the same error message.

**Comment by aleksakrstic** [comment]
Could you clone and run the tests for the Sample project I shared, and see if it runs ok for you?

**Comment by wim07101993** [comment]
The clone worked. Apparently the first problem was that I forgot the `await tester.pump();` and after that I had a nested MaterialApp widget.
